Disable workflow

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -1,84 +1,84 @@
----
-name: "Vprofile IAC"
+# ---
+# name: "Vprofile IAC"
 
-on:
-  push:
-    branches:
-      - stage
-      - main
-    paths:
-      - terraform/**
-  pull_request:
-    branches:
-      - main
-    paths:
-      - terraform/**
+# on:
+#   push:
+#     branches:
+#       - stage
+#       - main
+#     paths:
+#       - terraform/**
+#   pull_request:
+#     branches:
+#       - main
+#     paths:
+#       - terraform/**
 
-env:
-  # Credentials for deploying to AWS
-  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  # S3 Bucket for storing Terraform state files
-  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
-  AWS_REGION: "eu-central-1"
-  EKS_CLUSTER: "vprofile-eks"
+# env:
+#   # Credentials for deploying to AWS
+#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#   # S3 Bucket for storing Terraform state files
+#   BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
+#   AWS_REGION: "eu-central-1"
+#   EKS_CLUSTER: "vprofile-eks"
 
-jobs:
-  terraform:
-    name: "Apply Terraform code changes"
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        shell: bash
-        working-directory: ./terraform
+# jobs:
+#   terraform:
+#     name: "Apply Terraform code changes"
+#     runs-on: ubuntu-latest
+#     defaults:
+#       run:
+#         shell: bash
+#         working-directory: ./terraform
     
-    steps:
-      - name: "Checkout source code"
-        uses: actions/checkout@v6
+#     steps:
+#       - name: "Checkout source code"
+#         uses: actions/checkout@v6
       
-      - name: "Setup Terraform with specified version on the runner"
-        uses: hashicorp/setup-terraform@v3
-        #with:
-        #  terraform_version: 1.14.0
+#       - name: "Setup Terraform with specified version on the runner"
+#         uses: hashicorp/setup-terraform@v3
+#         #with:
+#         #  terraform_version: 1.14.0
       
-      - name: "Terraform Init"
-        id: tf_init
-        run: terraform init -backend-config="bucket=${{ env.BUCKET_TF_STATE }}" -auto-approve 
+#       - name: "Terraform Init"
+#         id: tf_init
+#         run: terraform init -backend-config="bucket=${{ env.BUCKET_TF_STATE }}" -auto-approve 
 
-      - name: "Terraform format check"
-        id: tf_fmt
-        run: terraform fmt -check
+#       - name: "Terraform format check"
+#         id: tf_fmt
+#         run: terraform fmt -check
 
-      - name: "Terraform Validate"
-        id: tf_validate
-        run: terraform validate
+#       - name: "Terraform Validate"
+#         id: tf_validate
+#         run: terraform validate
 
-      - name: "Terraform Plan"
-        id: tf_plan
-        run: terraform plan -no-color -input=false -out tfplan
-        continue-on-error: true
+#       - name: "Terraform Plan"
+#         id: tf_plan
+#         run: terraform plan -no-color -input=false -out tfplan
+#         continue-on-error: true
 
-      - name: "Terraform plan status"
-        if: steps.tf_plan.outcome == 'failure'
-        run: exit 1
+#       - name: "Terraform plan status"
+#         if: steps.tf_plan.outcome == 'failure'
+#         run: exit 1
 
-      - name: "Terraform Apply"
-        id: tf_apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform destroy -input=false -auto-approve -parallelism=10
+#       - name: "Terraform Apply"
+#         id: tf_apply
+#         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+#         run: terraform destroy -input=false -auto-approve -parallelism=10
 
-      # - name: Configure AWS credentials
-      #   uses: aws-actions/configure-aws-credentials@v5
-      #   with:
-      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      #     aws-region: ${{ env.AWS_REGION }}
+#       # - name: Configure AWS credentials
+#       #   uses: aws-actions/configure-aws-credentials@v5
+#       #   with:
+#       #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#       #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#       #     aws-region: ${{ env.AWS_REGION }}
     
-      # - name: Get Kube config file
-      #   id: getconfig
-      #   if: steps.tf_apply.outcome == 'success'
-      #   run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }} 
+#       # - name: Get Kube config file
+#       #   id: getconfig
+#       #   if: steps.tf_apply.outcome == 'success'
+#       #   run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }} 
 
-      # - name: Install Ingress controller
-      #   if: steps.tf_apply.outcome == 'success' && steps.getconfig.outcome == 'success'
-      #   run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/refs/heads/main/deploy/static/provider/aws/deploy.yaml
+#       # - name: Install Ingress controller
+#       #   if: steps.tf_apply.outcome == 'success' && steps.getconfig.outcome == 'success'
+#       #   run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/refs/heads/main/deploy/static/provider/aws/deploy.yaml
